version: "3.6"
services:
  ahi_angular_web:
    image: ahi/web:latest
    container_name: ahi_angular
    restart: always
    networks:
      - ahinet
    ports:
      - "3008:80"
    environment:
      APPLICATION_PORT: 3008
      NODE_ENV: prod
networks:
  ahinet:
    name: ahi-project-network
    driver: bridge
