version: "3.6"
services:
  tms_angular_web:
    image: tms/web:latest
    container_name: tms_angular
    restart: always
    networks:
      - tmsnet
    ports:
      - "3008:80"
    environment:
      APPLICATION_PORT: 3008
      NODE_ENV: prod
networks:
  tmsnet:
    name: tms-project-network
    driver: bridge
